LINKS = -L../libft -I../libft -lft

readline:
		make -C ../libft all
		clang readline.c -lreadline $(LINKS)
		./a.out

getenv:
		make -C ../libft all
		clang getenv.c -lreadline $(LINKS)
		./a.out

splitargs:
		make -C ../libft all
		clang splitargs.c -lreadline $(LINKS)
		./a.out

chdir:
		make -C ../libft all
		clang chdir.c -lreadline $(LINKS)
		./a.out
